# Generated by Django 3.1.7 on 2021-05-03 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=14, unique=True, verbose_name='CNPJ')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('complemento', models.CharField(blank=True, max_length=35, null=True, verbose_name='Complemento')),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Logradouro')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('fone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fone')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Dt.Inclusão')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Dt.Update')),
                ('data_ult_backup', models.DateTimeField(blank=True, null=True, verbose_name='Dt.Backup')),
                ('monitora', models.BooleanField(blank=True, choices=[(None, ''), (True, 'Sim'), (False, 'Não')], default=False, verbose_name='Monitora')),
                ('is_active', models.BooleanField(blank=True, choices=[(None, ''), (True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'cliente',
                'ordering': ['nome'],
                'permissions': (('MONITORAMENTO', 'Visualizar monitoramento'),),
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('ADMINIST', 'Administrativo'), ('FINANCEIRO', 'Financeiro'), ('COMERCIA', 'Comercial'), ('ATENDIMENTO', 'Atendimento'), ('UTIL', 'Utilitário'), ('CADASTROS', 'Cadastro'), ('CONTRATOS', 'Contrato'), ('IPM', 'IPM'), ('VIDA', 'PILATIS VIDA'), ('BACKUP', 'Backup')], max_length=30, null=True, verbose_name='Módulo')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('setor', models.CharField(max_length=100, null=True, verbose_name='Setor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
                'ordering': ['created_at', 'cliente'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.BigIntegerField(null=True, verbose_name='Tarefa')),
                ('modulo', models.CharField(choices=[('ADMINIST', 'Administrativo'), ('FINANCEIRO', 'Financeiro'), ('COMERCIA', 'Comercial'), ('ATENDIMENTO', 'Atendimento'), ('UTIL', 'Utilitário'), ('CADASTROS', 'Cadastro'), ('CONTRATOS', 'Contrato'), ('IPM', 'IPM'), ('VIDA', 'PILATIS VIDA'), ('BACKUP', 'Backup')], max_length=30, null=True, verbose_name='Módulo')),
                ('status', models.CharField(choices=[('INICIO', 'Aguardando'), ('PRODUCAO', 'Em produção'), ('PAUSA', 'Em pausa'), ('ANALISE', 'Em análise'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='INICIO', max_length=20, null=True, verbose_name='Status')),
                ('solicitante', models.CharField(max_length=100, verbose_name='Quem solicitou')),
                ('celular', models.CharField(max_length=20, null=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='BAIXA', max_length=30, verbose_name='Prioridade')),
                ('resumo', models.CharField(max_length=100, verbose_name='Opção de menu')),
                ('demanda', models.TextField(null=True, verbose_name='Demanda')),
                ('tempo_produtivo', models.IntegerField(null=True, verbose_name='Tempo Prod.')),
                ('tempo_ocioso', models.IntegerField(null=True, verbose_name='Tempo Prod.')),
                ('tempo_analise', models.IntegerField(null=True, verbose_name='Tempo Analise.')),
                ('ultimo_tempo', models.DateTimeField(null=True, verbose_name='Ult.Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em')),
                ('iniciado_dt', models.DateTimeField(null=True, verbose_name='Inidicado em')),
                ('encerrado_dt', models.DateTimeField(null=True, verbose_name='Encerrado em')),
                ('categoria_sac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.categoriasac')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'db_table': 'tarefa',
                'ordering': ['resumo', 'cliente', 'celular', 'email'],
                'permissions': (('IMPLEMENTAR_FUNCIONALIDADE', 'Implementar funcionalidades'), ('TESTAR_FUNCIONALIDADE', 'Realizar testes de funcionalidade')),
            },
        ),
        migrations.CreateModel(
            name='TarefaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tarefa')),
            ],
            options={
                'db_table': 'tarefa_evento',
            },
        ),
    ]
