# Generated by Django 3.1.7 on 2021-08-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tarefa_implantado_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='implantado_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
