# Generated by Django 3.1.7 on 2021-05-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_documento_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='descricao',
        ),
    ]
