# Generated by Django 3.1.7 on 2021-05-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_documento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tarefa'),
        ),
    ]
