# Generated by Django 3.1.7 on 2021-05-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_documento_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='tarefa',
        ),
    ]
