# Generated by Django 3.1.7 on 2021-05-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_documento_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='documentos',
            field=models.ManyToManyField(to='core.Documento'),
        ),
    ]
