# Generated by Django 3.1.7 on 2021-05-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tarefa_documentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
