# Generated by Django 3.1.7 on 2021-05-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210506_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True),
        ),
    ]
