# Generated by Django 3.1.7 on 2021-05-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_documento_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='slug',
            field=models.SlugField(editable=False, max_length=255),
        ),
    ]
