# Generated by Django 3.1.7 on 2021-05-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210506_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='slug',
        ),
    ]
