# Generated by Django 3.1.7 on 2021-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_documento_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='serie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Série'),
        ),
    ]
