# Generated by Django 3.1.7 on 2021-05-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cliente_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='serie_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dt.Serie'),
        ),
    ]
