# Generated by Django 3.1.7 on 2021-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cliente_serie_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nivel',
            field=models.CharField(choices=[('A', 'Automático'), ('F', 'Financeiro'), ('L', 'Leitura')], max_length=1, null=True),
        ),
    ]
