# Generated by Django 3.1.7 on 2021-05-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cliente_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nivel',
            field=models.CharField(choices=[('A', 'Automático'), ('F', 'Financeiro'), ('L', 'Leitura')], max_length=1, null=True, verbose_name='Autorização'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tempo_analise',
            field=models.IntegerField(default=0, verbose_name='Tempo Analise.'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tempo_ocioso',
            field=models.IntegerField(default=0, verbose_name='Tempo Prod.'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tempo_produtivo',
            field=models.IntegerField(default=0, verbose_name='Tempo Prod.'),
        ),
    ]
