# Generated by Django 3.1.7 on 2021-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210531_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fantasia',
            field=models.CharField(max_length=100, null=True, verbose_name='Fantasia'),
        ),
    ]
