# Generated by Django 3.1.7 on 2021-06-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_usercliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fantasia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fantasia'),
        ),
    ]
