# Generated by Django 3.1.7 on 2021-05-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_adm',
            field=models.BooleanField(blank=True, default=False, verbose_name='Administrativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_des',
            field=models.BooleanField(blank=True, default=False, verbose_name='Desenvolvimento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_fin',
            field=models.BooleanField(blank=True, default=False, verbose_name='Financeiro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_sac',
            field=models.BooleanField(blank=True, default=False, verbose_name='Atendimento SAC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_sup',
            field=models.BooleanField(blank=True, default=False, verbose_name='Suporte'),
        ),
    ]
