# Generated by Django 3.1.7 on 2021-06-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210528_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_consulta',
            field=models.BooleanField(blank=True, default=False, verbose_name='Desenvolvimento'),
        ),
    ]
