# Generated by Django 3.1.7 on 2021-08-23 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_tarefa_implantado_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('autorizado_dt', models.DateTimeField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('created_dt', models.DateTimeField(blank=True, null=True)),
                ('documento', models.TextField(blank=True, null=True)),
                ('hashcode', models.CharField(blank=True, max_length=32, null=True)),
                ('revogacao_dt', models.DateTimeField(blank=True, null=True)),
                ('updated_dt', models.DateTimeField(blank=True, null=True)),
                ('anonimizacao_dt', models.DateTimeField(blank=True, null=True)),
                ('autorizador', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'consentimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=252, null=True)),
                ('opcao', models.CharField(blank=True, max_length=100, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tratamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsentimentoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consentimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgpd.consentimento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
            ],
            options={
                'db_table': 'consentimento_evento',
            },
        ),
    ]
