"""
Django settings for compliance project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v7i=*_gangtwz2-x!@ytfsd$w-a)_q=&zc+9o&v$vf7)w=*6*a'

# SECURITY WARNING: don't run with debug turned on in production!

# ALLOWED_HOSTS = ['127.0.0.1', '3.224.26.231']
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'validate_docbr',
    'bootstrapform',
    'compliance.core',
    'compliance.atendimento',
    'compliance.aws',
    'compliance.accounts',
    'compliance.lgpd',
    'compliance.pessoa',
    'crispy_forms',
    'werkzeug_debugger_runserver',
    'django_extensions',
    'sslserver',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

ROOT_URLCONF = 'compliance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'compliance.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {

    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'OPTIONS': {
    #         'options': '-c search_path=compliance'
    #     },
    #     'NAME': 'assist',
    #     'USER': 'postgres',
    #     'PASSWORD': 'contrate',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }

    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=compliance'
        },
        'NAME': 'assist',
        'USER': 'postgres',
        'PASSWORD': 'abc123456',
        'HOST': 'compliance.cckc3qamx2hw.us-east-1.rds.amazonaws.com',
        'PORT': '5432',
    }

}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

SESSION_COOKIE_AGE = 900
SESSION_SAVE_EVERY_REQUEST = True

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Fortaleza'
USE_I18N = True
USE_L10N = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'assist@assistweb.com.br'
EMAIL_HOST = 'webmail.assistweb.com.br'
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'assist@assistweb.com.br'
EMAIL_HOST_PASSWORD = 'Q9Ks9IR9O7'
EMAIL_PORT = 587
CONTACT_EMAIL = 'assist@assistweb.com.br'

LOGIN_URL = 'login/'
LOGIN_REDIRECT_URL = '/'
LOGOU_URL = 'logout/'

AUTH_USER_MODEL = 'accounts.User'

AWS_STORAGE_BUCKET_NAME = 'suporteassist'
AWS_ACCESS_KEY_ID = 'AKIA46H6AGELQM3ROUM4'
AWS_SECRET_ACCESS_KEY = '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'

DEBUG = True
SECURE_SSL_REDIRECT = True

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, "/static/")
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, "static/"),
# )


COMPLIANCE_API = 'http://3.224.26.231:8081/'
# COMPLIANCE_API = 'http://localhost:8081/'
COMPLIANCE_URL = COMPLIANCE_API + 'compliance/'
LGPD_URL = COMPLIANCE_API + 'lgpd/'
