# Generated by Django 3.1.7 on 2021-09-20 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0002_auto_20210920_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoOcorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'db_table': 'ocorrencia',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('modulo', models.CharField(choices=[('ADMINIST', 'Administrativo'), ('FINANCEIRO', 'Financeiro'), ('COMERCIA', 'Comercial'), ('ATENDIMENTO', 'Atendimento'), ('UTIL', 'Utilitário'), ('CADASTROS', 'Cadastro'), ('CONTRATOS', 'Contrato'), ('IPM', 'IPM'), ('PILATIS', 'Pilatis'), ('COMPLIANCE', 'Compliance'), ('VIDA', 'Pilatis Vida'), ('BACKUP', 'Backup')], max_length=30, null=True, verbose_name='Módulo')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('observacao', models.TextField(verbose_name='Observação')),
                ('previsao_dt', models.DateTimeField(verbose_name='Previsão inicio')),
                ('inicio_dt', models.DateTimeField(verbose_name='Inicio')),
                ('termino_dt', models.DateTimeField(verbose_name='Término')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em')),
                ('contato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.contato')),
                ('ocorrencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimento.atendimentoocorrencia')),
            ],
            options={
                'db_table': 'atendimento',
            },
        ),
    ]
