# Generated by Django 3.1.7 on 2021-09-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_atendimento_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='user',
            new_name='usuario',
        ),
    ]
