# Generated by Django 3.1.7 on 2021-09-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_auto_20210922_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='inicio_dt',
            field=models.DateTimeField(null=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='observacao',
            field=models.TextField(null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='termino_dt',
            field=models.DateTimeField(null=True, verbose_name='Término'),
        ),
    ]
